---
- name: Package management by ansible
  hosts: node1
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes



    - name: Remove nginx package
      apt:
        name: nginx
        state: absent


