---
- name: Package management by ansible
  hosts: all
  tasks:
    - name: install nginx
      apt: 
        name: nginx
        state: present
        update_cache: yes

      service:
        name: nginx
        state: restarted  

    - name: remove nginx
      apt:
        name: nginx
        state: absent
        

