---

- name: file operations
  hosts: node2
  become: yes
  tasks:
    - name: create a directory
      file:
        path: /opt/demo
        state: directory
        mode: '0755'

    - name: copy file to remote
      copy:
        src: ./file-operations.yml
        dest: /opt/demo/my-operations.yml

    - name: copy file from remote to local
      fetch:
        src: /opt/demo/my-operations.yml
        dest: /home/ubuntu/my-operations.yml

    - name: delete file
      file:
        path: /opt/demo/my-operations.yml
        state: absent
