---

- name: executing command on remote server
  hosts: all
  become: yes

  tasks:
    - name: executing shell command to allow permission to log file
      shell: ls -la | grep mayur

    - name: executing shell script on remote machine

      script: /home/ubuntu/Ansible-Playbooks/docker.sh
