--- 

- name: shaaring file
  hosts: all
  become: yes

  tasks:
    - name: share file from local to remote
      copy:
        src: /var/log/nginx/error.log"
        dest: /home/ubuntu/logs

    - name: share file from remote to local
      fetch:
        src: var/log/nginx/error.log"
        dest: /home/ubuntu/logs